create table tb_publico (id int8 generated by default as identity, cnpj varchar(255), cpf varchar(255), email varchar(255), nome varchar(255), respondido varchar(255), sugestao varchar(255), primary key (id));
INSERT INTO tb_publico (cnpj, cpf, email, nome, respondido, sugestao) VALUES (' ', '40029743915', 'orestesaraujo@gmail.com', 'Orestes Gastao Santos Araujo', 'N', ' ');
INSERT INTO tb_publico (cnpj, cpf, email, nome, respondido, sugestao) VALUES (' ', '45962138953', 'marilene_83@hotmail.com', 'Marilene Cechetto Araujo', 'N', ' ');
